version: '3.8'

services:
  # 1. Base de données (PostgreSQL)
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mon-reseau
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - mon-reseau
    depends_on:
      db:
        condition: service_healthy

networks: 
  mon-reseau:

volumes: 
  db-data: